"""
Query Agent LangGraph State Definitions

All TypedDict data structures for passing state between LangGraph nodes.
raw_sources uses Annotated[..., operator.add] to support automatic accumulation across multiple search rounds.
"""

from __future__ import annotations

import operator
from typing import Annotated, Dict, List, Literal, Optional, TypedDict


# ---------------------------------------------------------------------------
# Subtype Definitions
# ---------------------------------------------------------------------------


class SubQueryItem(TypedDict):
    """Single subquery: Generated by QueryPlanner, carries stance and search source routing info."""

    query: str
    target_stance: Literal["official", "support", "oppose", "neutral", "background"]
    target_source: Literal["tavily", "bocha", "insight_db", "any"]
    priority: int                        # 1 (highest) ~ 5 (lowest)
    search_params: Optional[Dict]        # e.g., include_domains, time_range, etc.


class SourceItem(TypedDict):
    """Single search source, enriched throughout the entire processing flow."""

    source_id: str                       # UUID
    url: str
    title: str
    source_api: str                      # "tavily" / "bocha" / "insight_db"
    platform: str                        # Extracted domain, e.g., "reuters.com"
    snippet: str                         # Summary (≤500 characters)
    full_content: Optional[str]          # Full text (if returned by search API)
    published_at: Optional[str]          # ISO 8601 formatted date
    trust_score: float                   # 0–1, populated by TrustScorer
    stance_label: Optional[str]          # Populated by StanceClassifier
    stance_confidence: float             # 0–1
    sub_query_ref: str                   # Which subquery this came from
    rrf_score: Optional[float]           # RRF fusion score (Phase 2 populated)


class OpinionCluster(TypedDict):
    """Opinion cluster for the same stance."""

    cluster_id: str
    stance: str
    core_argument: str                   # Core argument (1 sentence)
    evidence_sources: List[str]          # List of source_ids
    representative_quote: str            # Representative quote (≤100 characters)
    estimated_proportion: float          # Proportion of this stance among all sources
    source_count: int


class QueryAgentOutput(TypedDict):
    """Structured output passed to downstream systems."""

    original_query: str
    analysis_type: str
    search_iterations: int
    total_sources_found: int             # Total count before deduplication
    total_sources_kept: int             # Count after deduplication and filtering
    stance_distribution: Dict[str, float]  # {"support": 0.3, ...}
    opinion_clusters: List[OpinionCluster]
    sources: List[SourceItem]            # Sorted by trust_score descending
    knowledge_gaps: List[str]
    coverage_score: float                # 0–1 stance coverage score
    structured_summary: str              # LLM-generated comprehensive summary
    trace_log: List[str]


# ---------------------------------------------------------------------------
# Main State
# ---------------------------------------------------------------------------


class QueryAgentState(TypedDict):
    """Complete runtime state for LangGraph subgraph.

    raw_sources uses operator.add reducer, so multi-round search results are automatically appended rather than overwritten.
    Same for error_log.
    """

    # === Input ===
    original_query: str
    analysis_type: str  # "event" / "brand" / "policy" / "person" / "general"

    # === Query Planning ===
    sub_queries: List[SubQueryItem]
    search_iterations: int
    max_iterations: int                  # Default 3

    # === Search Results (Multi-round accumulation) ===
    raw_sources: Annotated[List[SourceItem], operator.add]

    # === Processed Results ===
    deduped_sources: List[SourceItem]
    scored_sources: List[SourceItem]
    classified_sources: List[SourceItem]

    # === Coverage Assessment ===
    stance_coverage: Dict[str, int]      # {"support": 3, ...}
    missing_stances: List[str]
    gap_queries: List[SubQueryItem]

    # === Final Output ===
    query_agent_output: Optional[QueryAgentOutput]

    # === Monitoring ===
    trace_log: Annotated[List[str], operator.add]
    error_log: Annotated[List[str], operator.add]
