"""
StanceClassify Node

Calls HybridStanceClassifier for each source in scored_sources,
fills stance_label and stance_confidence, producing classified_sources.

Key Design: Before classification, build from state["sub_queries"]
  sub_query_ref → target_stance mapping, inject into each source's _target_stance field,
  providing the classifier with "sub-query weak label" (confidence 0.50).

Phase 2 new node, located in the graph at trust_scorer → stance_classify → coverage_check.
"""

from __future__ import annotations

from collections import Counter
from typing import Dict, List

from loguru import logger

from ...classifiers.stance_classifier import HybridStanceClassifier
from ..state import QueryAgentState


def _build_stance_lookup(state: QueryAgentState) -> Dict[str, str]:
    """
    Build from sub_queries (including all historical rounds) and gap_queries
      query text → target_stance mapping.
    """
    lookup: Dict[str, str] = {}

    for sq in state.get("sub_queries") or []:
        q = sq.get("query", "")
        stance = sq.get("target_stance", "")
        if q and stance:
            lookup[q] = stance

    # gap_queries are generated by GapFiller during supplementary search, also need to be included in mapping
    for gq in state.get("gap_queries") or []:
        q = gq.get("query", "")
        stance = gq.get("target_stance", "")
        if q and stance:
            lookup[q] = stance

    return lookup


async def stance_classify_node(state: QueryAgentState) -> dict:
    """
    LangGraph Node: Hybrid stance classification.

    Input: state["scored_sources"] (or fallback to deduped_sources)
    Output: state["classified_sources"] (each with stance_label + stance_confidence filled)
    """
    sources: List[dict] = (
        state.get("scored_sources")
        or state.get("deduped_sources")
        or []
    )
    query = state.get("original_query", "")

    # Build sub-query → target_stance lookup table (for weak labeling)
    stance_lookup = _build_stance_lookup(state)

    classifier = HybridStanceClassifier()
    classified: List[dict] = []

    for s in sources:
        s = dict(s)  # shallow copy

        # Inject sub-query weak label
        sub_ref = s.get("sub_query_ref", "")
        s["_target_stance"] = stance_lookup.get(sub_ref, "")

        # Classification
        stance, confidence = classifier.classify(s, query)
        s["stance_label"] = stance
        s["stance_confidence"] = confidence

        classified.append(s)

    # Count stance distribution (for logging)
    stance_counts = Counter(s["stance_label"] for s in classified)
    trace = (
        f"[StanceClassify] Classified {len(classified)} sources, "
        f"distribution={dict(stance_counts)}"
    )
    logger.info(trace)

    return {
        "classified_sources": classified,
        "trace_log": [trace],
    }
