"""
UnifiedSearch Node — Unified Search Dispatch

Calls UnifiedSearchDispatcher to execute sub-queries in parallel,
raw_sources are automatically accumulated into State via operator.add reducer.
"""

from __future__ import annotations

import asyncio
from loguru import logger

from ...tools.search_dispatcher import UnifiedSearchDispatcher
from ..state import QueryAgentState


async def unified_search_node(state: QueryAgentState) -> dict:
    """
    LangGraph Node: Unified search.

    First round uses sub_queries; subsequent supplementary search rounds use gap_queries (generated by GapFiller).
    """
    # Determine the set of sub-queries for this search round
    gap_queries = state.get("gap_queries") or []
    if gap_queries:
        queries_to_search = gap_queries
        logger.info(f"[UnifiedSearch] Supplementary search mode: {len(queries_to_search)} gap queries")
    else:
        queries_to_search = state.get("sub_queries", [])
        logger.info(f"[UnifiedSearch] First round search: {len(queries_to_search)} sub-queries")

    iteration = state.get("search_iterations", 0) + 1

    dispatcher = UnifiedSearchDispatcher()
    new_sources, errors = await dispatcher.dispatch(queries_to_search)

    trace = (
        f"[UnifiedSearch] Round {iteration}, "
        f"searched {len(queries_to_search)} sub-queries, "
        f"obtained {len(new_sources)} sources"
    )
    logger.info(trace)

    return {
        "raw_sources": new_sources,       # operator.add → auto append
        "search_iterations": iteration,
        "gap_queries": [],                 # Clear to avoid duplicate searches
        "trace_log": [trace],
        "error_log": errors,
    }
